# Generated by Django 5.0.7 on 2024-08-23 18:28

import facturacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(default=facturacion.models.get_default_fecha_vencimiento),
        ),
    ]
