# Generated by Django 5.0.7 on 2024-08-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cliente_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
    ]
