# Generated by Django 5.0.7 on 2024-08-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cliente_groups_cliente_is_staff_cliente_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='role',
            new_name='rol',
        ),
    ]
