# Generated by Django 5.0.7 on 2024-08-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('en_mantenimiento', 'En mantenimiento'), ('reservada', 'Reservada')], default='activa', max_length=50),
        ),
    ]
